// Carga inicial de pendientes de CRM (Ruta Mujer / Nos mueve la ruta),
// consolidados del acta de comité de tecnología y los tickets recibidos.
// Solo se usa la primera vez que se abre la app (si no hay datos guardados).

export function seedBoard() {
  return {
    "por-hacer": [
      {
        id: "seed_02",
        title: "Validar campos CRM vs. SAE",
        description: "El equipo operativo de Ruta Mujer revisa de nuevo los campos disponibles para garantizar que todo lo requerido en SAE esté contemplado.",
        project: "Ruta Mujer (Colsubsidio)",
        priority: "media",
        dueDate: "",
        status: "por-hacer",
      },
      {
        id: "seed_03",
        title: "Cargar usuarios, colaboradores y perfiles de acceso",
        description: "Listado remitido por Patricia Castillo (Listado_colaboradores_cargue_en_CRM.xlsx) para Registro, Orientación, Intermediación, cargue de vacantes, creación de empresas y agenda.",
        project: "Ruta Mujer (Colsubsidio)",
        priority: "media",
        dueDate: "",
        status: "por-hacer",
      },
      {
        id: "seed_05",
        title: "Identificar HABILITANTE / NO HABILITANTE en CRM",
        description: "Necesario para el listado semanal que se remite a Colsubsidio para validación.",
        project: "Ruta Mujer (Colsubsidio)",
        priority: "media",
        dueDate: "",
        status: "por-hacer",
      },
      {
        id: "seed_06",
        title: "Ajustes al módulo de VACANTES",
        description: "Agregar rango de edad, localidad/cobertura, geolocalización, enfoque de género y marca de vacantes de Des masculinización.",
        project: "Ruta Mujer (Colsubsidio)",
        priority: "media",
        dueDate: "",
        status: "por-hacer",
      },
      {
        id: "seed_07crm",
        title: "Estados AGENDADO / PENDIENTE en módulo EMPRESAS",
        description: "Para empresas en estado PENDIENTE, capturar el motivo por el cual continúa pendiente.",
        project: "Ruta Mujer (Colsubsidio)",
        priority: "media",
        dueDate: "",
        status: "por-hacer",
      },
      {
        id: "seed_08",
        title: "Agregar campo código SISE en VACANTES",
        description: "No debe ser condicionante, solo un campo informativo para reconocer si la vacante ya fue cargada en SISE.",
        project: "Ruta Mujer (Colsubsidio)",
        priority: "alta",
        dueDate: "",
        status: "por-hacer",
      },
      {
        id: "seed_09",
        title: "Eliminar flujo indirecto para registrar COLOCADO",
        description: "Registrar la colocación directo desde el módulo COLOCACIÓN: buscar el documento en INSCRIPCIÓN, completar datos y buscar la vacante en VACANTES, sin pasar por INTERMEDIACIÓN.",
        project: "Ruta Mujer (Colsubsidio)",
        priority: "alta",
        dueDate: "",
        status: "por-hacer",
      },
      {
        id: "seed_10",
        title: "Identificar # de bonos de mitigación de colocación",
        description: "Cuántas personas colocadas recibieron el auxilio de mitigación y por qué valores — solicitado por Pablo Zuluaga.",
        project: "Nos mueve la ruta de oportunidades (Alcaldía de Malambo)",
        priority: "media",
        dueDate: "",
        status: "por-hacer",
      },
      {
        id: "seed_11",
        title: "Verificar/agregar campo sexo/género en módulo ORIENTACIÓN",
        description: "Necesario para el cruce de formación, intereses y experiencia entre hombres y mujeres del informe final de NMLR.",
        project: "Nos mueve la ruta de oportunidades (Alcaldía de Malambo)",
        priority: "alta",
        dueDate: "",
        status: "por-hacer",
      },
    ],
    "en-curso": [],
    bloqueado: [
      {
        id: "seed_01",
        title: "Ajustar tipificación de GRUPO POBLACIONAL",
        description: "Pendiente por revisión base que debe remitir Paola Cabrera.",
        project: "Ruta Mujer (Colsubsidio)",
        priority: "media",
        dueDate: "",
        status: "bloqueado",
      },
      {
        id: "seed_04",
        title: "Crear módulo PSICOSOCIAL",
        description: "Debe diferenciar atenciones individuales y grupales, registrar talleres e incorporar evidencias. Pendiente por campos y requerimientos de Paola Cabrera.",
        project: "Ruta Mujer (Colsubsidio)",
        priority: "media",
        dueDate: "",
        status: "bloqueado",
      },
    ],
    hecho: [],
  };
}
